### ISSUE TITLE
Yeelight devices not working

### ISSUE THREAD

**Issue by AlexVasile26** [deankevorkian/RGBMaster#1]
Hello,

When I try syncing with Yeelight devices (strip, bulbs), the app is hanging at 
`this.musicModeSocket = musicModeSocketListener.Accept();` in YeelightDevice.cs

Any idea why or if I need to setup anything except LAN Control? @deankevorkian 

Many thanks

**Comment by deankevorkian** [comment]
Hey! Thanks for finding and supporting this project, first of all.
Second - there is one thing I have yet to take care of, that may cause this issue - are you by any chance connected to multiple networks? Maybe a VPN or some sort?

**Comment by AlexVasile26** [comment]
I had RadminVPN opened, will try again

**Comment by deankevorkian** [comment]
I had the same issues with RadminVPN too! Stopping it fixed it for me, but it wasn't enough to turn it off - I had to disable the RadminVPN Tunnel network adapter.

**Comment by AlexVasile26** [comment]
That's what I did now. It worked. Thanks a lot! 😄

**Comment by deankevorkian** [comment]
Sure :)
